version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: offboarding_postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offboarding_db1
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - offboarding_net

  backend:
    build: ./Backend
    container_name: offboarding_backend1
    ports:
      - "3010:3010"
    volumes:
      - ./Backend/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - offboarding_net

  employee-offboarding:
    build: ./Employee-Offboarding
    container_name: employee_offboarding_1
    ports:
      - "9015:80"
    networks:
      - offboarding_net

  hr-offboarding:
    build: ./HR-Offboarding
    container_name: hr_offboarding_1
    ports:
      - "9016:80"
    networks:
      - offboarding_net

volumes:
  pgdata:

networks:
  offboarding_net:

